version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  crudmongo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crudmongo-api
    depends_on:
      - mongodb
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
    restart: always

volumes:
  mongo_data:
